export const FILTER_ROBOTS = "FILTER ROBOTS"

export const REQUEST_ROBOTS_PENDING = "REQUEST ROBOTS PENDING"
export const REQUEST_ROBOTS_SUCCESS = "REQUEST ROBOTS SUCCESS"
export const REQUEST_ROBOTS_FAILED = "REQUEST ROBOTS FAILED"
